name: EasyBind
main: com.easybind.EasyBind
version: 1.1
author: Meaglin
website: https://github.com/Meaglin/EasyBind
description: The plugin to easily make serverside binds.
database: true
commands:
    bind:
        aliases: [ b , "b+" ]
        description: binds a [command] to the equiped tool.
        usage: /<command> [command]
    unbind:
        aliases: [ removebind, delbind , "b-" ]
        description: unbinds command from the equiped tool.
        usage: /<command>
    listbinds:
        aliases: [ binds ]
        description: list the current set binds.
        usage: /<command> [page|current]